// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqJJ0Xn1QQDWYeT5aOpxpGEVb5k3jvfX0',
    appId: '1:779924111298:web:e93ece31afef855263605b',
    messagingSenderId: '779924111298',
    projectId: 'flashchatapp-84d77',
    authDomain: 'flashchatapp-84d77.firebaseapp.com',
    storageBucket: 'flashchatapp-84d77.appspot.com',
    measurementId: 'G-JZGGG042R0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEI4nXrpdOfg3YclIYj4tyUVYNOXMmriY',
    appId: '1:779924111298:android:207ae3bf37aa605a63605b',
    messagingSenderId: '779924111298',
    projectId: 'flashchatapp-84d77',
    storageBucket: 'flashchatapp-84d77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUAFqI5vEi9NyQKvWP4DHqjIFVgqvl1BU',
    appId: '1:779924111298:ios:6a816075f62ac2af63605b',
    messagingSenderId: '779924111298',
    projectId: 'flashchatapp-84d77',
    storageBucket: 'flashchatapp-84d77.appspot.com',
    iosBundleId: 'com.example.flashchatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUAFqI5vEi9NyQKvWP4DHqjIFVgqvl1BU',
    appId: '1:779924111298:ios:6a816075f62ac2af63605b',
    messagingSenderId: '779924111298',
    projectId: 'flashchatapp-84d77',
    storageBucket: 'flashchatapp-84d77.appspot.com',
    iosBundleId: 'com.example.flashchatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqJJ0Xn1QQDWYeT5aOpxpGEVb5k3jvfX0',
    appId: '1:779924111298:web:69445aedf5c9bfd663605b',
    messagingSenderId: '779924111298',
    projectId: 'flashchatapp-84d77',
    authDomain: 'flashchatapp-84d77.firebaseapp.com',
    storageBucket: 'flashchatapp-84d77.appspot.com',
    measurementId: 'G-WGWQV4C5FW',
  );
}
